language: node_js
node_js:
  - 8.10.0
scripts:
#- npm run ci
  - npm install codecov -g
after_success:
  - codecov
# blocklist
branches:
  except:
  - /^feature.*/
# safelist
branches:
  only:
  - master
  - stable
